### ISSUE TITLE
docker-compose.yml_Bug_Report

### ISSUE THREAD

**Issue by elmo1032** [elmo1032/flask-restful#12]
The Docker Compose file you provided seems to be mostly correct, but here are a few potential issues you might want to address:

1. The `version` field should be at the top level of the file, not inside the `services` block. Here's the corrected version:
```yaml
version: '3.7'
services:
  ...
```
2. The `restart` policy for the `app` service is set to `always`, which means the container will always restart if it exits. This might not be desirable if the container is exiting due to an error that needs to be fixed. Consider using a more appropriate restart policy, such as `on-failure` or `unless-stopped`.
3. There is no `networks` block defined in the file. While not strictly necessary, it's a good practice to define a network for your services to communicate with each other. Here's an example:
```yaml
version: '3.7'
services:
  app:
    ...
  database:
    ...
networks:
  my-network:
    driver: bridge
```
4. There is no `command` specified for the `app` service. This means that Docker Compose will use the default command for the image, which might not be what you want. Consider specifying a custom command to run your application.

Here's the corrected version of the file with these issues addressed:
```yaml
version: '3.7'

services:
  app:
    build: ./app
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - database
    command: python app.py

  database:
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:

networks:
  my-network:
    driver: bridge
```
Note that you might need to adjust the `command` field to match your specific application.
