### ISSUE TITLE
docker-compose.yml Bug Report

### ISSUE THREAD

**Issue by elmo1032** [elmo1032/flask-restful#24]
The Docker Compose file you provided seems to be mostly correct, but here are a few potential issues you might want to address:

1. The `version` field should be at the top level of the file, not inside the `services` block. Here's the corrected version:
```yaml
version: '3.7'
services:
  ...
```
2. The `restart` policy for the `app` service is set to `always`, which means the container will always restart if it exits. This might not be desirable if the container is exiting due to an error that needs to be fixed. Consider using a more appropriate restart policy, such as `on-failure` or `unless-stopped`.
3. There is no `networks` block defined in the file. While not strictly necessary, it's a good practice to define a network for your services to communicate with each other. Here's an example:
```yaml
version: '3.7'
services:
  app:
    ...
  database:
    ...
networks:
  my-network:
    driver: bridge
```
4. The `database` service uses the `latest` tag for the PostgreSQL image, which might not be desirable. Using the `latest` tag can lead to unexpected behavior if the image is updated with breaking changes. Consider using a specific version tag instead, such as `postgres:13.2`.
5. There is no `healthcheck` defined for the `database` service. While not strictly necessary, it's a good practice to define a health check to ensure that the service is running correctly. Here's an example:
```yaml
version: '3.7'
services:
  database:
    image: postgres:13.2
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  database-data:
```
