### ISSUE TITLE
docker-compose.yml Bug Report

### ISSUE THREAD

**Issue by elmo1032** [elmo1032/flask-restful#6]
The Docker Compose file you provided seems to be mostly correct, but here are a few potential issues you might want to address:

1. The `version` field should be at the top level of the file, not inside the `services` block. Here's the corrected version:
```yaml
version: '3.7'
services:
  ...
```
2. The `restart` policy for the `app` service is set to `always`, which means that the container will always restart if it exits. This might not be desirable if the container is exiting due to an error that needs to be fixed. Consider using a more appropriate restart policy, such as `on-failure`.
3. There is no `networks` block defined in the file. While not strictly necessary, it's a good practice to define a network for your services to communicate with each other. Here's an example:
```yaml
version: '3.7'
services:
  app:
    ...
  database:
    ...
network:
  app-network:
    driver: bridge
```
4. The `env_file` option for the `database` service is using a relative path (`postgres.env`). If the Docker Compose file is not in the same directory as the `postgres.env` file, the service will not be able to find it. Consider using an absolute path or moving the `postgres.env` file to the same directory as the Docker Compose file.

Other than these potential issues, the Docker Compose file looks good!
