### ISSUE TITLE
docker-compose.yml Bug Report

### ISSUE THREAD

**Issue by elmo1032** [elmo1032/flask-restful#7]
The Docker Compose file you provided seems to be mostly correct, but here are a few potential issues you might want to address:

1. The `version` field should be at the top level of the file, not inside the `services` block. Here's the corrected version:
```yaml
version: '3.7'
services:
  ...
```
2. The `restart` policy for the `app` service is set to `always`, which means the container will always restart if it exits. This might not be desirable if the container is exiting due to an error that needs to be fixed. Consider using a more appropriate restart policy, such as `on-failure`.
3. There is no `networks` block defined in the file. While not strictly a bug, it's generally a good practice to define a network for your services to communicate with each other. Here's an example:
```yaml
version: '3.7'
services:
  app:
    ...
  database:
    ...
networks:
  my-network:
    driver: bridge
```
4. There is no `image` defined for the `app` service. This means that Docker Compose will try to build an image from the `Dockerfile` in the `./app` directory. If you want to use a pre-built image instead, you can specify it using the `image` field.
5. There is no `healthcheck` defined for the `database` service. While not a bug, it's a good practice to define a health check for your databases to ensure they are running correctly. Here's an example:
```yaml
database:
  image: postgres:latest
  env_file:
    - postgres.env
  ports:
    - 5432:5432
  volumes:
    - database-data:/var/lib/postgresql/data/
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 5s
    retries: 5
```

These are just a few potential issues to consider. Depending on your specific use case, there may be other modifications you need to
